### ISSUE TITLE
MISP: Error importError cannot import name “ExpandedMISP”

### ISSUE THREAD

**Issue by asghar3166** [MISP/misp-dashboard#79]
I am receiving the following error below. Much appreciated in advance.

`ERROR: Failure: ImportError (cannot import name 'ExpandedPyMISP')
ImportError: cannot import name "ExpandedPyMISP`

![expandedmisperror](https://user-images.githubusercontent.com/22902750/52760844-08997d00-2fdf-11e9-8bac-e9ed0c32ab84.jpg)

**Comment by asghar3166** [comment]
So I found out that this should work using Python3.6....let me give that a try. thanks
